import type {NextPage} from 'next';
import Head from 'next/head';
import Router from 'next/router';
import LinkList from '../components/parts/LinkList';
import styles from '../styles/Home.module.css';

const links = [
  {name: 'Static Page', href: '/static-page'},
  {name: 'Dynamic Page', href: '/dynamic-page'},
  {name: 'Item Page', href: '/item/1001/sort-by'},
  {name: 'Shallow Routing', href: '/shallow-routing?counter=5'},
];

const Home: NextPage = () => {
  const goToItemPage = () => {
    Router.push('/item/999/all/sort-by');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LinkList links={links} />
        <button onClick={goToItemPage}>Go to Item Page</button>
      </main>
    </div>
  );
};

export default Home;
