# ベースイメージの設定
FROM ubuntu

# Nginxのインストール
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install nginx

# ポート指定
EXPOSE 80

# Webコンテンツの配置
# このコマンドは本Dockerfileをビルドして生成されたイメージを、更にFROMで指定してビルドされる際に実行する
ONBUILD ADD website.tar /var/www/html

# Nginxの実行
CMD ["nginx", "-g", "daemon off;"]